openapi: 3.0.0
info:
  title: 家族間メッセージ共有 API
  version: 0.1.0
paths:
  /messages:
    post:
      summary: Post a message to one or more recipients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient_ids:
                  type: array
                  items:
                    type: string
                body:
                  type: string
                attachment_ref:
                  type: string
      responses:
        '201':
          description: Message created

  /invitations:
    post:
      summary: Invite a user to accept messages / join
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: string
                target_participants:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Invitation created

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
        sender_id:
          type: string
        body:
          type: string
        created_at:
          type: string
